In [2]:
import utils.simulation_utils as sim

ModuleNotFoundError: No module named 'utils.simulation_utils'

In [1]:
signal = sim.signals_case_generation(n_transition_steps=500)


NameError: name 'sim' is not defined

In [4]:
for _ in range(5):
    s = sim.timesteps_generator(signal)
    print(f'First record {s[0]}. Array with shape {s.shape}')

TypeError: 'generator' object is not subscriptable

In [13]:
sim.timesteps_generator(signal)

AttributeError: module 'utils.simulation_utils' has no attribute 'timesteps_generator'

In [15]:
signal_generator = sim.data_generator(signal)

AttributeError: module 'utils.simulation_utils' has no attribute 'data_generator'

In [13]:
signal

array([430.98874386, 430.9965111 , 430.50043788, ..., 462.83654266,
       462.62559143, 463.101183  ])

In [14]:
signal.shape

(20426,)

In [6]:
g = sim.data_generator(signal, 5)

In [17]:
t = next(g)

In [19]:
type(t)

numpy.float64

In [9]:
import numpy as np


In [10]:
out = np.zeros(10)


In [33]:
out2 = np.zeros((10,) , dtype=np.float32)

In [11]:
out

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
for i in range(10):
    n = next(g)
    print(f'n: {n}')
    out[i] = n

n: 430.996511101037
n: 430.50043787818885
n: 430.23058530489544
n: 429.73349987345847
n: 429.27986939194204
n: 428.9240048881702
n: 428.4861099805606
n: 428.8326319220062
n: 428.4092676163273
n: 428.0280309512558


In [13]:
out

array([430.9965111 , 430.50043788, 430.2305853 , 429.73349987,
       429.27986939, 428.92400489, 428.48610998, 428.83263192,
       428.40926762, 428.02803095])

In [17]:
def timesteps_generator(data: np.array, start_timestep: int, n_timesteps: int = 5000):
        return data[start_timestep: start_timestep + n_timesteps]

In [24]:
d = timesteps_generator(signal, 1)

In [26]:
type(d)

numpy.ndarray

In [27]:
dl = d.tolist()
type(dl)

list

In [28]:
dl[:10]

[430.996511101037,
 430.50043787818885,
 430.23058530489544,
 429.73349987345847,
 429.27986939194204,
 428.9240048881702,
 428.4861099805606,
 428.8326319220062,
 428.4092676163273,
 428.0280309512558]

In [30]:
d.size

5000